Awesome books: refactor to use JavaScript classes PR
belmeetmule/awesome-books pull request #2
Opened 2022-08-10 23:28 UTC by belmeetmule

### I and my coding partner have done the following tasks:

- [ ] add book and collection classes
- [ ] style book list display
- [ ] display local storage 
- [ ] a little bit of DOM manipulation

2022-08-10 23:51 UTC, zainsadaqat requested changes
# Required Changes 🔁
# Hello @belmeetmule and @OmarMWarraich  😄 

You're doing a great job on your project. We're proud of you. Good job so far! 

There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
  ✅  Correct use of Github Flow
  ✅  No linter errors
  ✅  Descriptive Pull Request

## Required Changes ♻️

- [ ] Please use the README template provided by Microverse and don't forget to mention the project title, description, how to set up the project, sharing your social media links etc 👍 

_Check the comments under the review._


<img src="https://media0.giphy.com/media/QvMIzHw30MmMAqvOeo/giphy.gif"/>

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding! 👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-10 23:51 UTC, zainsadaqat commented on index.js
> +    });
Instead of creating a function for removing a book, Please create a class method to remove a book from the Book Store 👍🏻

2022-08-10 23:51 UTC, zainsadaqat commented on index.js
> +  }
It's not removing a book. Removing a book feature isn't working, Kindly fix this 👍🏻

2022-08-11 03:13 UTC, Davidosky007 approved these changes
Hi @belmeetmule @OmarMWarraich 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
* No linter errors 👍 
* Well written PR description 👍 
* Proper use of Github flow 👍 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-11 03:24 UTC, merged